name: Unit tests

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10  # Replace with python version relevant to your project
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Replace with python version relevant to your project
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Unit test with pytest
        run: |
          pytest --cov=./model/ ./tests/unit_tests/
